[[GroupingAndIndexingClause]]
== Grouping and Indexing Extension

=== GeoPackage deterministic hierarchical tiles grouping & indexing extension

==== Description

This extension defines the ability to optionally split data layers stored in GeoPackages using a deterministic approach to organize the directory structure and naming individual GeoPackage files.

Each data layer can also be associated with a _GeoDataClass_ URI using the https://docs.ogc.org/DRAFTS/24-049.html[Semantic Annotations] extension so that clients can easily find a particular class of data in the indexed GeoPackages.
For tiled vector data using the https://docs.ogc.org/DRAFTS/24-048.html[Tiled Feature Date extension], this can be done both at the level of the multi-layer tileset, as well as at the individual component vector layer.

This extension defines tables describing the GeoPackage configuration, allowing to best balance tradeoffs between the number of GeoPackages created and the file and table sizes within each GeoPackage for a particular dataset or use case.

The simplest option is storing everything in a single GeoPackage. Data layers can also be organized into multiple _packages_ stored together. A tile level grouping count can also be specified to split these packages into GeoPackages storing a partial tile pyramids consisting of that many levels sharing a single base tile. This approach limits the size of individual GeoPackages while balancing the number of files.

Conforming clients can open the primary GeoPackage and access the data regardless of which particular configuration of this extension is used, to suit a variety of datasets and use cases ranging from global high resolution repository spanning petabytes of data to small local extracts for mobile use. Regardless of the configuration option used, a client can easily find a particular data layer, without the need to look up an index for a particular area.

==== Dependencies

This extension depends on the https://github.com/ecere/geopackage/blob/main/spec/2dtms/26-ZZZ.adoc[2D Tile Matrix Set extension].

https://www.opengis.net/is/geopackage-2dtms/1.0

==== Definitions

- A _*level*_ corresponds to a 2DTMS Tile Matrix
- A _*package*_ represents one or more data layers packaged together, either as a single GeoPackage, or in multiple GeoPackages grouping a partial tile pyramid of zoom levels (from a minimum to a maximum level), or of untiled vector data (in Features tables).
- A _*GeoDataClass*_ (previously called a _Stylable Layer Set_) is a URI which has an associated schema (consisting of specific data layers, each with a schema defining specific fields and associated semantics); can be any type of geospatial data (coverage, vector features, 3D models...)

==== SQL Create statements

```SQL
CREATE TABLE gpkgext_hierarchical_gpkg_index(
   table_name REFERENCES gpkg_contents(table_name) NOT NULL,
   package_id REFERENCES gpkgext_hierarchical_gpkg_packages(id) NOT NULL,
   max_level INTEGER
)

CREATE TABLE gpkgext_hierarchical_gpkg_packages(
   id INTEGER PRIMARY KEY,
   name TEXT UNIQUE,
   level_grouping_count INTEGER,
   max_grouping_level INTEGER,
   tms_id INTEGER REFERENCES gpkgext_tile_matrix_set(id)
)
```

////
   geodataclass_uri TEXT,
////


==== Fields

===== `gpkgext_hierarchical_gpkg_index` table

[#table_gpkgext_hierarchical_gpkg_index,reftext='{table-caption} {counter:table-num}']
.Description of `gpkgext_hierarchical_gpkg_index`
[options="header"]
|===
| Name | Description
| `table_name` | entry in the `gpkg_contents` table of the data layers of each; The `gpkgext_contents` will exist in the primary GeoPackage, but the individual tiles table will be dummy tables with no actual entry if the data is stored externally in the GeoPackages grouping tiles
| `package_id`| reference to the package entry in the `gpkgext_hierarchical_gpkg_packages` table in which this data layer is stored
| `max_level`| the maximum level for this data layer across all sub-packages; this may be greater than the associated package `max_level` to allow for insets, in which case the insets will be stored in the package of the most detailed zoom level
|===

////
| `geodataclass_uri`| The https://github.com/opengeospatial/styles-and-symbology/issues/12[GeoDataClass] identifying the data layer (see table to define below)
////

////
NOTE: For vector tiles, the content table could contain multiple related data layers which together have a single GeoDataClass and are stored together in MVT
or https://github.com/opengeospatial/CDBV2-2023-Summer-Workshop/wiki/WKB-Collection[WKBC] blobs supporting multiple collections, or it may be individual data
layers -- we would need to decide whether CDB Vector GeoDataClasses should be individual and/or multi-layer. When not using tiles, each entry needs its own
table, so this would require individual GeoDataClasses per vector layer. Loading multiple vector layers that will be shown together (like OSM data layer) can
perform better, so we need to consider this.
////

===== `gpkgext_hierarchical_gpkg_packages` table

[#table_gpkgext_hierarchical_gpkg_packages,reftext='{table-caption} {counter:table-num}']
.Description of gpkgext_hierarchical_gpkg_packages
[options="header"]
|===
| Name | Description
| `id` | an integer primary key for this package entry referenced by the `gpkgext_hierarchical_gpkg_index` table
| `name`| name of the package in which this data layer is stored, `NULL` if things are stored in this primary GeoPackage file (only valid if `levelGroupingCount` is also `NULL`)
| `level_grouping_count`| number of levels to group together, starting from `max_level` down towards 0; `NULL` means the package is stored in a single GeoPackage file
| `max_grouping_level`| maximum level used for building tile pyramids (and thus GeoPackage file names when `levelGroupingCount` is not `NULL`)
| `tms_id`| The TileMatrixSet entry from https://gitlab.com/imagemattersllc/ogc-vtp2/-/blob/master/extensions/14-tile-matrix-set.adoc[2DTMS GeoPackage extension].
|===

NOTE: This extension requires the use of a TileMatrixSet using integer tile matrix identifiers, and where each tile is fully contained within the parent (level-1) tile matrix tile, such as a quad-tree, or semi-quad tree as used in the _GNOSIS Global Grid_ and _CDB 1 GlobalGrid_ variable width Tile Matrix Sets. _WorldCRS84Quad_, _WebMercatorQuad_, _WorldMercatorWGS84Quad_, _ISEA9R_, _rHEALPix_ would also all work, but not _GlobalCRS84Scale_ or _GlobalCRS84Pixel_ where children and parent tiles do not align.

==== Sub-GeoPackages naming and directory structures

The file and directory naming are deterministic and simple to compute algorithmically, without having to lookup any index to discover arbitrarily named files.

===== File names

The GeoPackage filenames follow the following template based on the package name, the coarsest tile in that package forming the basis of the partial tile pyramid for that GeoPackage, along with the level of the finest level tile that would normally be placed into this GeoPackage (excluding insets):

`{packageName}_L{gpkgMinLevel}_R{gpkgTileRow}_C{gpkgTileCol}_L{gpkgMaxLevel}.gpkg`

where:
- `{packageName}` refers to the package name as specified in the `name` field of the `gpkgext_hierarchical_gpkg_packages` table,
- `{gpkgMinLevel}` refers to the lowest level tile included within the grouping inside the GeoPackage,
- `{gpkgTileRow}` refers to the row of that lowest level tile (based on the TileMatrixSet for that package, for both CDB 1 and GNOSIS Global Grids they are counted from top/North to bottom/South),
- `{gpkgTileCol}` refers to the column of that lowest level tile (based on the TileMatrixSet for that package, from left/West to right/East), and
- `{gpkgMaxLevel}` refers to the maximum level tile normally included within the grouping inside this GeoPackage (excluding insets). For the deepest sub-directory, this will be the same value as the package `maxLevel` specified in the index.

An example based on the GNOSIS Global Grid: **Imagery_L12_R2607_C2858_L18.gpkg**

===== Directory structure

The directory organization, which limits the number of GeoPackage files and sub-directories that could exist within a single directory based on a particular level grouping count, follows the template:

```
{packageName}/
   L{parentMinLevel}_R{parentTileRow}_C{parentTileCol}/
      L{parentMinLevel}_R{parentTileRow}_C{parentTileCol}/
         ...
```

where:
- `{packageName}` refers to the package name as specified in the `name` field of the `gpkgext_hierarchical_gpkg_packages` table,
- `{parentMinLevel}` refers to the level (tile matrix) of the parent tile that contains all of content within this directory and its sub-directories,
- `{parentTileRow}` refers to the row of the parent tile that contains all of content within this directory and its sub-directories, and
- `{parentTileCol}` refers to the column of the parent tile that contains all of content within this directory and its sub-directories.

For example, based on the GNOSIS Global Grid, the file **Imagery_L12_R2607_C2858_L18.gpkg** would exist in the directory named **Imagery/L0_R0_C0/L5_R20_C22/**.

===== Example

Full directory listing example, based a _GNOSIS Global Grid_ `tms_id`, an _Imagery_ package `name`, and a package `max_grouping_level` of 18:

```
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2855_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2856_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2857_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2858_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2859_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2605_C2860_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2855_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2856_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2857_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2858_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2859_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2606_C2860_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2855_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2856_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2857_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2858_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2859_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2607_C2860_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2855_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2856_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2857_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2858_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2859_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2608_C2860_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2855_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2856_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2857_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2858_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2859_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22/Imagery_L12_R2609_C2860_L18.gpkg
Imagery/L0_R0_C0/L5_R20_C22
Imagery/L0_R0_C0/Imagery_L5_R20_C22_L11.gpkg
Imagery/L0_R0_C0
Imagery/Imagery_L0_R0_C0_L4.gpkg
Imagery/
SanDiego.gpkg
```

In the above example:
- the _Imagery_ package is stored within an `Imagery` sub-directory at the same level as the primary GeoPackage (`SanDiego.gpkg`),
- a single GeoPackage (`Imagery_L0_R0_C0_L4.gpkg`, less than 1 mb in this example) containing levels 0-4 is found directly within that `Imagery` sub-directory,
- a single GeoPackage (`Imagery_L5_R20_C22_L11.gpkg`, less than 1 mb in this example) containing levels 5-11 is found within the `Imagery/L0_R0_C0/` sub-directory for the area fully contained within the single parent level 4 tile of that GeoPackage above (`Imagery_L0_R0_C0_L4.gpkg`),
- 30 GeoPackages (each between 86 and 232 mb in this example) containing levels 12-18 are found within the `Imagery/L0_R0_C0/L5_R20_C22/` sub-directory for the area fully contained within the single parent level 11 tile of that GeoPackage above (`Imagery_L5_R20_C22_L11.gpkg`).

===== For even more deterministic naming

To facilitate extraction from a large global high-resolution dataset and easily merge these extracted sub-datasets as well as the ability to augment these base datasets with additional more detailed insets, without repackaging the entire dataset, the following solutions are proposed:

* The publisher of a large repository of data could define a profile pre-establishing the fixed package name, level grouping count and maximum package level for a specific GeoDataClass.
* When inset data is added to a dataset, these could go beyond the regular maximum level specified for the package (package `max_grouping_level`). As such these inset tiles are always grouped together with the tiles of the regular maximum level.

==== Profiling this extension

This extension addresses the use cases of splitting large datasets into multiple GeoPackages for efficient access using deterministic naming.
Some example datasets where this would be convenient:

- https://www.ogc.org/standards/cdb/[OGC CDB] (a model and structure for a virtual detailed representation of the earth),
- OrdnanceSurvey Master Map,
- OpenStreetMap Planet OSM,
- ESA sentinel-2

This indexing mechanism allows to describe multiple configurations:

- Choosing whether each GeoDataClass is in its own package, or together with data for other GeoDataClasses
- Choosing whether a particular package is organized by level groups or as a single GeoPackage

These options allows to define profiles that can balance the simplicity of working with a single container vs. the impracticality of dealing with huge files, and to adapt this to a particular dataset and usage, while a client implementing this extension will still be able to easily support all profiled configurations in a generic manner.

A particular profile could prescribe a particular grouping number for each GeoDataClass to be stored.
Initial experiments used a grouping of 7 for imagery stored as JPEG and a grouping of 6 for elevation stored as GeoTIFF.
A grouping of 5 was used when storing all datasets (3D models, vector, elevation, imagery) in the same package.
Different encoding formats with different compression ratio may work best with different values.

For users at the edge and smaller datasets over a small area, storing everything in a single GeoPackage is most convenient.  This approach could be result from an export from a larger dataset, where only the resolutions and the boundaries of the data needed are stored and delivered to an end user. Users at the edge are such individuals as field operatives using mobile devices with limited battery, memory, storage and processing capabilities as well as Delayed/Disconnected, Intermittently-connected or Limited bandwidth (DDIL) environments.

For Modeling and Simulation uses, as well as data repository cases, the Level grouping functionality can be used, and related data layers can be organized as a single package.  This involves storing a region of the world at a set of zoom levels, or levels of detail, within a single GeoPackage, with a specified file and directory naming scheme.  This approach would allow for faster access to data at specified areas and zoom levels.  This approach would also lend itself to concurrent access and editing for data repository maintainers.

==== Example Datasets and primary GeoPackages

===== Separate packages for each data layer

////
https://portal.ogc.org/index.php?m=projects&a=view&project_id=466&tab=2&artifact_id=95320[Data folder on the portal]

- https://portal.ogc.org/files/?artifact_id=95346[Airport lights]
- https://portal.ogc.org/files/?artifact_id=95351[3D Buildings]
- https://portal.ogc.org/files/?artifact_id=95347[Coronado Bridge]
- https://portal.ogc.org/files/?artifact_id=95347[Elevation]
- https://portal.ogc.org/files/?artifact_id=95348[Hydrography]
- https://portal.ogc.org/files/?artifact_id=95350[Roads]
- https://portal.ogc.org/files/?artifact_id=95349[Trees]
////

- https://data.ogc.org/2020/11/ImageryHigh.7z[High resolution imagery]
- https://data.ogc.org/2020/11/ImageryMedium.7z[Medium resolution imagery]
- https://data.ogc.org/2020/11/BlueMarble.7z[Blue Marble imagery]

// - https://portal.ogc.org/files/?artifact_id=95345[_cdb.json_ index] (replaced by the following primary GeoPackage tables)

A `SanDiego.gpkg` primary GeoPackage referencing the high-resolution imagery GeoPackage would contain a `gpkgext_hierarchical_gpkg_index` table that looks like this:

[#table_gpkgext_hierarchical_gpkg_index_example,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_index` table
[options="header"]
|===
| table_name                      | package_id | max_level
| tiles_ImageryHigh               | 2          | 18
|===

////
[#table_gpkgext_hierarchical_gpkg_index_example,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_index` table
[options="header"]
|===
| table_name                      | package_id | geodataclass_uri                                 | max_level
| tiles_Elevation                 | 1          | [ogc-geodataclass:cdb-elevation]                 | 16
| tiles_ImageryHigh               | 2          | [ogc-geodataclass:cdb-imagery]                   | 18
| tiles_Buildings                 | 3          | [ogc-geodataclass:cdb-ManMade_3DModels]          | 13
| tiles_CoronadoBridge            | 4          | [ogc-geodataclass:cdb-ManMade_Instanced3DModels] | 12
| tiles_Trees                     | 5          | [ogc-geodataclass:cdb-Trees_Instanced3DModels]   | 12
| tiles_AirportLights             | 6          | [ogc-geodataclass:cdb-AirportLights]             | 8
| tiles_Roads                     | 7          | [ogc-geodataclass:cdb-RoadNetwork_Lines]         | 16
| tiles_Hydrography               | 8          | [ogc-geodataclass:cdb-Hydrography_Polygons]      | 16
|===
////

and a `gpkgext_hierarchical_gpkg_packages` table that looks like this:

[#table_gpkgext_hierarchical_gpkg_packages_example,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_packages` table
[options="header"]
|===
| id  | name           | level_grouping_count | max_grouping_level | tms_id
|   1 | ImageryHigh    | 7                    | 18                 | 1 (GGG)
|===

////
[#table_gpkgext_hierarchical_gpkg_packages_example,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_packages` table
[options="header"]
|===
| id  | name           | level_grouping_count | max_grouping_level | tms_id
|   1 | Elevation      | 6                    | 16                 | 1 (GGG)
|   2 | ImageryHigh    | 7                    | 18                 | 1 (GGG)
|   3 | Buildings      | NULL                 | NULL               | 1 (GGG)
|   4 | CoronadoBridge | NULL                 | NULL               | 1 (GGG)
|   5 | Trees          | NULL                 | NULL               | 1 (GGG)
|   6 | AirportLights  | NULL                 | NULL               | 1 (GGG)
|   7 | Roads          | NULL                 | NULL               | 1 (GGG)
|   8 | Hydrography    | NULL                 | NULL               | 1 (GGG)
|===
////

This should correctly index the data following the same
https://github.com/sofwerx/cdb2-eng-report/blob/master/11-tiling-coverages.adoc#proposed-levels-of-detail-grouping[GeoPackage file naming conventions from the CDB X Techsprint]
summarized above.

===== One package grouping all data layers together by 5 tile levels

https://data.ogc.org/2020/11/SanDiego.7z[7-zip file of directories]

// https://portal.ogc.org/files/?artifact_id=95370[7-zip file of directories on the portal (smaller file, only for small spatial subset)]

// https://portal.ogc.org/files/?artifact_id=95366[_cdb.json_ index file on the portal]

NOTE: This `SanDiego.gpkg` GeoPackage should be augmented to contain a `gpkgext_hierarchical_gpkg_index` table that looks like this:

[#table_gpkgext_hierarchical_gpkg_index_one_package,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_index` table for grouping all data layers into one package
[options="header"]
|===
| table_name                      | package_id | max_level
| tiles_Elevation                 | 1          | 16
| tiles_ImageryHigh               | 1          | 18
| tiles_Buildings                 | 1          | 13
| tiles_CoronadoBridge            | 1          | 12
| tiles_Trees                     | 1          | 12
| tiles_AirportLights             | 1          | 8
| tiles_Roads                     | 1          | 16
| tiles_Hydrography               | 1          | 16
|===

////
| table_name                      | package_id | geodataclass_uri                                 | max_level
| tiles_Elevation                 | 1          | [ogc-geodataclass:cdb-elevation]                 | 16
| tiles_ImageryHigh               | 1          | [ogc-geodataclass:cdb-imagery]                   | 18
| tiles_Buildings                 | 1          | [ogc-geodataclass:cdb-ManMade_3DModels]          | 13
| tiles_CoronadoBridge            | 1          | [ogc-geodataclass:cdb-ManMade_Instanced3DModels] | 12
| tiles_Trees                     | 1          | [ogc-geodataclass:cdb-Trees_Instanced3DModels]   | 12
| tiles_AirportLights             | 1          | [ogc-geodataclass:cdb-AirportLights]             | 8
| tiles_Roads                     | 1          | [ogc-geodataclass:cdb-RoadNetwork_Lines]         | 16
| tiles_Hydrography               | 1          | [ogc-geodataclass:cdb-Hydrography_Polygons]      | 16
////

and a `gpkgext_hierarchical_gpkg_packages` table that looks like this:

[#table_gpkgext_hierarchical_gpkg_packages_one_package,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_packages` table for grouping all data layers into one package
[options="header"]
|===
| id  | name           | level_grouping_count | max_level | tms_id
|   1 | SanDiego       | 5                    | 18        | 1 (GGG)
|===

===== Single GeoPackage with everything

https://data.ogc.org/2020/11/SanDiego.gpkg.7z[GeoPackage file]

// https://portal.ogc.org/files/?artifact_id=95378[_cdb.json_ index file on the portal]

This `SanDiego.gpkg` (which would also act as the primary GeoPackage) would be augmented with the following `gpkgext_hierarchical_gpkg_index` table
that looks like this:

[#table_gpkgext_hierarchical_gpkg_index_single_gpkg,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_index` table for everything stored in a single GeoPackage
[options="header"]
|===
| table_name                      | package_id | max_level
| tiles_Elevation                 | 1          | 16
| tiles_ImageryHigh               | 1          | 18
| tiles_Buildings                 | 1          | 13
| tiles_CoronadoBridge            | 1          | 12
| tiles_Trees                     | 1          | 12
| tiles_AirportLights             | 1          | 8
| tiles_Roads                     | 1          | 16
| tiles_Hydrography               | 1          | 16
|===

////
| table_name                      | package_id | geodataclass_uri                                 | max_level
| tiles_Elevation                 | 1          | [ogc-geodataclass:cdb-elevation]                 | 16
| tiles_ImageryHigh               | 1          | [ogc-geodataclass:cdb-imagery]                   | 18
| tiles_Buildings                 | 1          | [ogc-geodataclass:cdb-ManMade_3DModels]          | 13
| tiles_CoronadoBridge            | 1          | [ogc-geodataclass:cdb-ManMade_Instanced3DModels] | 12
| tiles_Trees                     | 1          | [ogc-geodataclass:cdb-Trees_Instanced3DModels]   | 12
| tiles_AirportLights             | 1          | [ogc-geodataclass:cdb-AirportLights]             | 8
| tiles_Roads                     | 1          | [ogc-geodataclass:cdb-RoadNetwork_Lines]         | 16
| tiles_Hydrography               | 1          | [ogc-geodataclass:cdb-Hydrography_Polygons]      | 16
////

and a `gpkgext_hierarchical_gpkg_packages` table that looks like this:

[#table_gpkgext_hierarchical_gpkg_packages_single_gpkg,reftext='{table-caption} {counter:table-num}']
.Example `gpkgext_hierarchical_gpkg_packages` table for everything stored in a single GeoPackage
[options="header"]
|===
| id  | name           | level_grouping_count | max_level | tms_Id
|   1 | NULL           | NULL                 | 18        | 1 (GGG)
|===
