
== Conformance

This extension defines of a single mandatory conformance class, but is broken down into conceptual requirement classes which may eventually correspond to individual standardized OGC GeoPackage extensions.

The requirements apply to either of these two standardization target types:

* data products,
* software producing such data products.

Conformance with this extension shall be checked using all the relevant tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the NSG Compliance Testing Policies and Procedures and the NSG Compliance Testing web site.

In order to conform to this candidate NSG data product standard, a software implementation producing a compliant data product shall implement the core requirement classes defined in this extension.

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.
