[[OverviewClause]]
== Overview

This Engineering Report describes an extension for storing Releasable Basemap Tiles (RBT) in GeoPackage developed during the March 2024 OGC Code Sprint initiative sponsored by the US Army Geospatial Center (AGC).

The report is organized into four main sections:

* <<RBTGeoPackageClause, *Section 6 -- Releasable Basemap Tiles GeoPackage Extension*>> describes the RBT extension as a whole, including requirements for declaring conformance to this extension, as well as requirements specific to storing RBT data products,

* <<VectorTilesClause, *Section 7 -- Vector Tiles*>> describes requirements related to storing vector tiles in GeoPackages, based on the draft extensions developed in previous initiatives such as
the Vector Tile Pilots (https://www.ogc.org/initiatives/vt-pilot-2018/[Phase 1+extension] and https://www.ogc.org/initiatives/vtp2/[Phase2]),

* <<SemanticAnnotationsClause, *Section 8 -- Semantic Annotations*>> describes requirements related to semantic annotations, also based on previously developed draft extensions, providing a mechanism to identify content and associate portrayal rules with content,

* <<StylingClause, *Section 9 -- Styling*>> describes requirements related to including styles (portrayal information) in GeoPackages, also based on previously developed draft extensions,

and three annexes:

* <<annex-ats, *Annex A -- Abstract Test Suite*>> defines an Abstract Test Suite for this extension, upon which an Executable Test Suite could be based,

* <<ImplementationsClause, *Annex B -- Implementations*>> describes three implementations of both producers and consumers (viewers) of GeoPackages using this extension
developed during the code sprint by three participants: <<Implementations-Ecere,*Ecere Corporation*>>, <<Implementations-Compusult,*Compusult Limited*>> and <<Implementations-TechMaven,*TechMaven Geospatial*>>,
including Technology Integration Experiments demonstrating interoperability between these different implementations, as well as <<Implementations-Lessons,*Challenges and Lessons Learned*>> from these implementation efforts,

* <<FutureWork, *Annex C -- Future Work*>> provides recommendations for future work that could be undertaken to build upon the results from the sprint, improve interoperability and performance for RBT content, and move this extension along the standardization process.
