[appendix,obligation="normative"]
[[annex-ats]]
== Conformance Class Abstract Test Suite

=== Conformance Class Semantic Annotations GeoPackage Extension

[[conf_geopackage-semantic,/conf/geopackage-semantic]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/geopackage-semantic/1.0/conf/core
target:: https://www.opengis.net/spec/geopackage-semantic/1.0/req/core
classification:: Target Type:Data Product
abstract-test:: /conf/geopackage-semantic/extensions
abstract-test:: /conf/geopackage-semantic/semantic-annotations
abstract-test:: /conf/geopackage-semantic/sa-reference
====

==== Abstract Test for Requirement Extensions

[[conf_geopackage-semantic_extensions,/conf/geopackage-semantic/extensions]]
[abstract_test]
====
[%metadata]
identifier:: /conf/geopackage-semantic/extensions
target:: /req/geopackage-semantic/extensions
test-purpose:: Verify that the GeoPackage properly declare extended tables
test-method::
+
--
*Given:* a GeoPackage conforming to the core GeoPackage standard +
*When:* querying the content of the `gpkg_extensions` table +
*Then:* +
- assert that the relevant entries listed in <<extension_table>> are present, including an entry for every user data table making use of these extensions.
--
====

==== Abstract Test for Requirement Defining Semantic Annotations

[[conf_geopackage-semantic_semantic-annotations,/conf/geopackage-semantic/semantic-annotations]]
[abstract_test]
====
[%metadata]
identifier:: /conf/geopackage-semantic/semantic-annotations
target:: /req/geopackage-semantic/semantic-annotations
test-purpose:: Verify that the GeoPackage properly defines semantic annotations
test-method::
+
--
*Given:* a GeoPackage conforming to the core GeoPackage standard declaring the use of semantic annotatins in its extensions +
*When:* inspecting the `gpkgext_semantic_annotations` table +
*Then:* +
- assert that ... +
--
====

==== Abstract Test for Requirement Referencing Semantic Annotations

[[conf_geopackage-semantic_sa-reference,/conf/geopackage-semantic/sa-reference]]
[abstract_test]
====
[%metadata]
identifier:: /conf/geopackage-semantic/sa-reference
target:: /req/geopackage-semantic/sa-reference
test-purpose:: Verify that the GeoPackage properly references semantic annotations
test-method::
+
--
*Given:* a GeoPackage conforming to the core GeoPackage standard declaring the use of semantic annotatins in its extensions +
*When:* inspecting the `gpkgext_sa_reference` table +
*Then:* +
- assert that ... +
--
====
