
== Terms and Definitions

////
Note that the initial notice about terms ("This document uses the terms defined in OGC Policy Directive 49...")
is inserted automatically by Metanorma using the agreed standardised language, and you should not enter it here.
////

[[term-2DTMS]]
=== 2-Dimensional Tile Matrix Set (2DTMS)

tiling scheme consisting of a set of tile matrices defined at different scales covering approximately the same area and having a common coordinate reference system.

[.source]
<<OGC17-083r4>>

[[term-geodataclass]]
=== geodataclass

a URI identifying a class of geospatial data whose component data layers conform to a particular logical schema

A registry of geodataclasses would ideally resolve these URIs to metadata including these schemas.
A geodataclass serves multiple purposes, including the ability to easily identify, using a simple identifier comparison,
relevant datasets for a particular purpose, the compatibility of datasets as inputs for processes, the compatibility
of the output of a process with the input of another process, as well as the compatibility of portrayal style information
with a particular dataset (see also https://github.com/opengeospatial/styles-and-symbology/issues/12).

[[term-mvt]]
=== Mapbox vector tiles (MVT)

a https://github.com/mapbox/vector-tile-spec/tree/master/2.1[specification] developed by Mapbox for encoding tiled vector data using https://protobuf.dev/[protocol buffers].

[[term-rbt]]
=== releasable basemap tiles (RBT)

tilesets of foundational geospatial data developed by the US Army Geospatial Center for public release,
including vector tilesets of cultural and physical features, hillshaded elevation data and optional imagery

[[term-tie]]
=== technology integration experiment (TIE)

experiments performed between different implementations of a specification or standard to test and demonstrate interoperability between them, and in the case of TIEs
performed in the context of an initiative to validate a draft specification or standard, to validate the soundness and completeness of the requirements specified therein
